name: Laravel CI/CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy Laravel to Ubuntu Server
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy via SSH
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@your.server.ip << 'EOF'
            cd /var/www/your-laravel-project
            git pull origin main
            composer install --no-interaction --prefer-dist --optimize-autoloader
            php artisan migrate --force
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache
            chmod -R 775 storage bootstrap/cache
          EOF
